[cerebrium.deployment]
name = "zen-doc-trainer"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = true
include = ['./*', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 2.0
memory = 5.0
compute = "CPU"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 30
replica_concurrency = 1
scaling_metric = "concurrency_utilization"

[cerebrium.dependencies.pip]
kagglehub = ">=1.0.1"
matplotlib = ">=3.10.9"
onnx = ">=1.16.0"
onnxruntime = ">=1.26.0"
pandas = ">=3.0.3"
scikit-learn = ">=1.8.0"
seaborn = ">=0.13.2"
tensorflow = ">=2.21.0"
tf2onnx = ">=1.17.0"
cerebrium = ">=2.4.0"
