/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TenantCreateRouteImport } from './routes/tenant/create'
import { Route as DoctorProfileRouteImport } from './routes/doctor/profile'
import { Route as DoctorPlansRouteImport } from './routes/doctor/plans'
import { Route as DoctorHubRouteImport } from './routes/doctor/hub'
import { Route as DoctorCreditsRouteImport } from './routes/doctor/credits'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor/availability'
import { Route as AdminSessionRouteImport } from './routes/admin/session'
import { Route as TenantTenantIdIndexRouteImport } from './routes/tenant/$tenantId/index'
import { Route as DoctorSessionsIndexRouteImport } from './routes/doctor/sessions/index'
import { Route as AdminSessionsIndexRouteImport } from './routes/admin/sessions/index'
import { Route as AdminPlansIndexRouteImport } from './routes/admin/plans/index'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin/patients/index'
import { Route as AdminGuardiansIndexRouteImport } from './routes/admin/guardians/index'
import { Route as AdminDoctorsIndexRouteImport } from './routes/admin/doctors/index'
import { Route as AdminDocRequestsIndexRouteImport } from './routes/admin/doc-requests/index'
import { Route as AdminCreditsIndexRouteImport } from './routes/admin/credits/index'
import { Route as TenantTenantIdSettingsRouteImport } from './routes/tenant/$tenantId/settings'
import { Route as TenantTenantIdInviteRouteImport } from './routes/tenant/$tenantId/invite'
import { Route as TenantTenantIdDoctorsRouteImport } from './routes/tenant/$tenantId/doctors'
import { Route as TenantTenantIdClinicsRouteImport } from './routes/tenant/$tenantId/clinics'
import { Route as TenantTenantIdAttendanceRouteImport } from './routes/tenant/$tenantId/attendance'
import { Route as DoctorSessionsSessionIdRouteImport } from './routes/doctor/sessions/$sessionId'
import { Route as DoctorHubMaterialIdRouteImport } from './routes/doctor/hub/$materialId'
import { Route as AdminDoctorsDoctorIdRouteImport } from './routes/admin/doctors/$doctorId'

const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantCreateRoute = TenantCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TenantRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPlansRoute = DoctorPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorHubRoute = DoctorHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorCreditsRoute = DoctorCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminSessionRoute = AdminSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AdminRoute,
} as any)
const TenantTenantIdIndexRoute = TenantTenantIdIndexRouteImport.update({
  id: '/$tenantId/',
  path: '/$tenantId/',
  getParentRoute: () => TenantRoute,
} as any)
const DoctorSessionsIndexRoute = DoctorSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminSessionsIndexRoute = AdminSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansIndexRoute = AdminPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuardiansIndexRoute = AdminGuardiansIndexRouteImport.update({
  id: '/guardians/',
  path: '/guardians/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsIndexRoute = AdminDoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocRequestsIndexRoute = AdminDocRequestsIndexRouteImport.update({
  id: '/doc-requests/',
  path: '/doc-requests/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsIndexRoute = AdminCreditsIndexRouteImport.update({
  id: '/credits/',
  path: '/credits/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantTenantIdSettingsRoute = TenantTenantIdSettingsRouteImport.update({
  id: '/$tenantId/settings',
  path: '/$tenantId/settings',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTenantIdInviteRoute = TenantTenantIdInviteRouteImport.update({
  id: '/$tenantId/invite',
  path: '/$tenantId/invite',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTenantIdDoctorsRoute = TenantTenantIdDoctorsRouteImport.update({
  id: '/$tenantId/doctors',
  path: '/$tenantId/doctors',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTenantIdClinicsRoute = TenantTenantIdClinicsRouteImport.update({
  id: '/$tenantId/clinics',
  path: '/$tenantId/clinics',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTenantIdAttendanceRoute =
  TenantTenantIdAttendanceRouteImport.update({
    id: '/$tenantId/attendance',
    path: '/$tenantId/attendance',
    getParentRoute: () => TenantRoute,
  } as any)
const DoctorSessionsSessionIdRoute = DoctorSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorHubMaterialIdRoute = DoctorHubMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => DoctorHubRoute,
} as any)
const AdminDoctorsDoctorIdRoute = AdminDoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tenant': typeof TenantRouteWithChildren
  '/admin/session': typeof AdminSessionRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/credits': typeof DoctorCreditsRoute
  '/doctor/hub': typeof DoctorHubRouteWithChildren
  '/doctor/plans': typeof DoctorPlansRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/tenant/create': typeof TenantCreateRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/doctor/hub/$materialId': typeof DoctorHubMaterialIdRoute
  '/doctor/sessions/$sessionId': typeof DoctorSessionsSessionIdRoute
  '/tenant/$tenantId/attendance': typeof TenantTenantIdAttendanceRoute
  '/tenant/$tenantId/clinics': typeof TenantTenantIdClinicsRoute
  '/tenant/$tenantId/doctors': typeof TenantTenantIdDoctorsRoute
  '/tenant/$tenantId/invite': typeof TenantTenantIdInviteRoute
  '/tenant/$tenantId/settings': typeof TenantTenantIdSettingsRoute
  '/admin/credits/': typeof AdminCreditsIndexRoute
  '/admin/doc-requests/': typeof AdminDocRequestsIndexRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
  '/admin/guardians/': typeof AdminGuardiansIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/plans/': typeof AdminPlansIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/doctor/sessions/': typeof DoctorSessionsIndexRoute
  '/tenant/$tenantId/': typeof TenantTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/session': typeof AdminSessionRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/credits': typeof DoctorCreditsRoute
  '/doctor/hub': typeof DoctorHubRouteWithChildren
  '/doctor/plans': typeof DoctorPlansRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/tenant/create': typeof TenantCreateRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/doctor/hub/$materialId': typeof DoctorHubMaterialIdRoute
  '/doctor/sessions/$sessionId': typeof DoctorSessionsSessionIdRoute
  '/tenant/$tenantId/attendance': typeof TenantTenantIdAttendanceRoute
  '/tenant/$tenantId/clinics': typeof TenantTenantIdClinicsRoute
  '/tenant/$tenantId/doctors': typeof TenantTenantIdDoctorsRoute
  '/tenant/$tenantId/invite': typeof TenantTenantIdInviteRoute
  '/tenant/$tenantId/settings': typeof TenantTenantIdSettingsRoute
  '/admin/credits': typeof AdminCreditsIndexRoute
  '/admin/doc-requests': typeof AdminDocRequestsIndexRoute
  '/admin/doctors': typeof AdminDoctorsIndexRoute
  '/admin/guardians': typeof AdminGuardiansIndexRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/plans': typeof AdminPlansIndexRoute
  '/admin/sessions': typeof AdminSessionsIndexRoute
  '/doctor/sessions': typeof DoctorSessionsIndexRoute
  '/tenant/$tenantId': typeof TenantTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tenant': typeof TenantRouteWithChildren
  '/admin/session': typeof AdminSessionRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/credits': typeof DoctorCreditsRoute
  '/doctor/hub': typeof DoctorHubRouteWithChildren
  '/doctor/plans': typeof DoctorPlansRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/tenant/create': typeof TenantCreateRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/doctor/hub/$materialId': typeof DoctorHubMaterialIdRoute
  '/doctor/sessions/$sessionId': typeof DoctorSessionsSessionIdRoute
  '/tenant/$tenantId/attendance': typeof TenantTenantIdAttendanceRoute
  '/tenant/$tenantId/clinics': typeof TenantTenantIdClinicsRoute
  '/tenant/$tenantId/doctors': typeof TenantTenantIdDoctorsRoute
  '/tenant/$tenantId/invite': typeof TenantTenantIdInviteRoute
  '/tenant/$tenantId/settings': typeof TenantTenantIdSettingsRoute
  '/admin/credits/': typeof AdminCreditsIndexRoute
  '/admin/doc-requests/': typeof AdminDocRequestsIndexRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
  '/admin/guardians/': typeof AdminGuardiansIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/plans/': typeof AdminPlansIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/doctor/sessions/': typeof DoctorSessionsIndexRoute
  '/tenant/$tenantId/': typeof TenantTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/sign-in'
    | '/sign-up'
    | '/tenant'
    | '/admin/session'
    | '/doctor/availability'
    | '/doctor/credits'
    | '/doctor/hub'
    | '/doctor/plans'
    | '/doctor/profile'
    | '/tenant/create'
    | '/admin/'
    | '/doctor/'
    | '/tenant/'
    | '/admin/doctors/$doctorId'
    | '/doctor/hub/$materialId'
    | '/doctor/sessions/$sessionId'
    | '/tenant/$tenantId/attendance'
    | '/tenant/$tenantId/clinics'
    | '/tenant/$tenantId/doctors'
    | '/tenant/$tenantId/invite'
    | '/tenant/$tenantId/settings'
    | '/admin/credits/'
    | '/admin/doc-requests/'
    | '/admin/doctors/'
    | '/admin/guardians/'
    | '/admin/patients/'
    | '/admin/plans/'
    | '/admin/sessions/'
    | '/doctor/sessions/'
    | '/tenant/$tenantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin/session'
    | '/doctor/availability'
    | '/doctor/credits'
    | '/doctor/hub'
    | '/doctor/plans'
    | '/doctor/profile'
    | '/tenant/create'
    | '/admin'
    | '/doctor'
    | '/tenant'
    | '/admin/doctors/$doctorId'
    | '/doctor/hub/$materialId'
    | '/doctor/sessions/$sessionId'
    | '/tenant/$tenantId/attendance'
    | '/tenant/$tenantId/clinics'
    | '/tenant/$tenantId/doctors'
    | '/tenant/$tenantId/invite'
    | '/tenant/$tenantId/settings'
    | '/admin/credits'
    | '/admin/doc-requests'
    | '/admin/doctors'
    | '/admin/guardians'
    | '/admin/patients'
    | '/admin/plans'
    | '/admin/sessions'
    | '/doctor/sessions'
    | '/tenant/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/sign-in'
    | '/sign-up'
    | '/tenant'
    | '/admin/session'
    | '/doctor/availability'
    | '/doctor/credits'
    | '/doctor/hub'
    | '/doctor/plans'
    | '/doctor/profile'
    | '/tenant/create'
    | '/admin/'
    | '/doctor/'
    | '/tenant/'
    | '/admin/doctors/$doctorId'
    | '/doctor/hub/$materialId'
    | '/doctor/sessions/$sessionId'
    | '/tenant/$tenantId/attendance'
    | '/tenant/$tenantId/clinics'
    | '/tenant/$tenantId/doctors'
    | '/tenant/$tenantId/invite'
    | '/tenant/$tenantId/settings'
    | '/admin/credits/'
    | '/admin/doc-requests/'
    | '/admin/doctors/'
    | '/admin/guardians/'
    | '/admin/patients/'
    | '/admin/plans/'
    | '/admin/sessions/'
    | '/doctor/sessions/'
    | '/tenant/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TenantRoute: typeof TenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant/create': {
      id: '/tenant/create'
      path: '/create'
      fullPath: '/tenant/create'
      preLoaderRoute: typeof TenantCreateRouteImport
      parentRoute: typeof TenantRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/plans': {
      id: '/doctor/plans'
      path: '/plans'
      fullPath: '/doctor/plans'
      preLoaderRoute: typeof DoctorPlansRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/hub': {
      id: '/doctor/hub'
      path: '/hub'
      fullPath: '/doctor/hub'
      preLoaderRoute: typeof DoctorHubRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/credits': {
      id: '/doctor/credits'
      path: '/credits'
      fullPath: '/doctor/credits'
      preLoaderRoute: typeof DoctorCreditsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/availability': {
      id: '/doctor/availability'
      path: '/availability'
      fullPath: '/doctor/availability'
      preLoaderRoute: typeof DoctorAvailabilityRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/session': {
      id: '/admin/session'
      path: '/session'
      fullPath: '/admin/session'
      preLoaderRoute: typeof AdminSessionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant/$tenantId/': {
      id: '/tenant/$tenantId/'
      path: '/$tenantId'
      fullPath: '/tenant/$tenantId/'
      preLoaderRoute: typeof TenantTenantIdIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/doctor/sessions/': {
      id: '/doctor/sessions/'
      path: '/sessions'
      fullPath: '/doctor/sessions/'
      preLoaderRoute: typeof DoctorSessionsIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/sessions/': {
      id: '/admin/sessions/'
      path: '/sessions'
      fullPath: '/admin/sessions/'
      preLoaderRoute: typeof AdminSessionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/': {
      id: '/admin/plans/'
      path: '/plans'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof AdminPlansIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/patients'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guardians/': {
      id: '/admin/guardians/'
      path: '/guardians'
      fullPath: '/admin/guardians/'
      preLoaderRoute: typeof AdminGuardiansIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors/': {
      id: '/admin/doctors/'
      path: '/doctors'
      fullPath: '/admin/doctors/'
      preLoaderRoute: typeof AdminDoctorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doc-requests/': {
      id: '/admin/doc-requests/'
      path: '/doc-requests'
      fullPath: '/admin/doc-requests/'
      preLoaderRoute: typeof AdminDocRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credits/': {
      id: '/admin/credits/'
      path: '/credits'
      fullPath: '/admin/credits/'
      preLoaderRoute: typeof AdminCreditsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant/$tenantId/settings': {
      id: '/tenant/$tenantId/settings'
      path: '/$tenantId/settings'
      fullPath: '/tenant/$tenantId/settings'
      preLoaderRoute: typeof TenantTenantIdSettingsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/$tenantId/invite': {
      id: '/tenant/$tenantId/invite'
      path: '/$tenantId/invite'
      fullPath: '/tenant/$tenantId/invite'
      preLoaderRoute: typeof TenantTenantIdInviteRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/$tenantId/doctors': {
      id: '/tenant/$tenantId/doctors'
      path: '/$tenantId/doctors'
      fullPath: '/tenant/$tenantId/doctors'
      preLoaderRoute: typeof TenantTenantIdDoctorsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/$tenantId/clinics': {
      id: '/tenant/$tenantId/clinics'
      path: '/$tenantId/clinics'
      fullPath: '/tenant/$tenantId/clinics'
      preLoaderRoute: typeof TenantTenantIdClinicsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/$tenantId/attendance': {
      id: '/tenant/$tenantId/attendance'
      path: '/$tenantId/attendance'
      fullPath: '/tenant/$tenantId/attendance'
      preLoaderRoute: typeof TenantTenantIdAttendanceRouteImport
      parentRoute: typeof TenantRoute
    }
    '/doctor/sessions/$sessionId': {
      id: '/doctor/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/doctor/sessions/$sessionId'
      preLoaderRoute: typeof DoctorSessionsSessionIdRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/hub/$materialId': {
      id: '/doctor/hub/$materialId'
      path: '/$materialId'
      fullPath: '/doctor/hub/$materialId'
      preLoaderRoute: typeof DoctorHubMaterialIdRouteImport
      parentRoute: typeof DoctorHubRoute
    }
    '/admin/doctors/$doctorId': {
      id: '/admin/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/admin/doctors/$doctorId'
      preLoaderRoute: typeof AdminDoctorsDoctorIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSessionRoute: typeof AdminSessionRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDoctorsDoctorIdRoute: typeof AdminDoctorsDoctorIdRoute
  AdminCreditsIndexRoute: typeof AdminCreditsIndexRoute
  AdminDocRequestsIndexRoute: typeof AdminDocRequestsIndexRoute
  AdminDoctorsIndexRoute: typeof AdminDoctorsIndexRoute
  AdminGuardiansIndexRoute: typeof AdminGuardiansIndexRoute
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
  AdminPlansIndexRoute: typeof AdminPlansIndexRoute
  AdminSessionsIndexRoute: typeof AdminSessionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSessionRoute: AdminSessionRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDoctorsDoctorIdRoute: AdminDoctorsDoctorIdRoute,
  AdminCreditsIndexRoute: AdminCreditsIndexRoute,
  AdminDocRequestsIndexRoute: AdminDocRequestsIndexRoute,
  AdminDoctorsIndexRoute: AdminDoctorsIndexRoute,
  AdminGuardiansIndexRoute: AdminGuardiansIndexRoute,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
  AdminPlansIndexRoute: AdminPlansIndexRoute,
  AdminSessionsIndexRoute: AdminSessionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorHubRouteChildren {
  DoctorHubMaterialIdRoute: typeof DoctorHubMaterialIdRoute
}

const DoctorHubRouteChildren: DoctorHubRouteChildren = {
  DoctorHubMaterialIdRoute: DoctorHubMaterialIdRoute,
}

const DoctorHubRouteWithChildren = DoctorHubRoute._addFileChildren(
  DoctorHubRouteChildren,
)

interface DoctorRouteChildren {
  DoctorAvailabilityRoute: typeof DoctorAvailabilityRoute
  DoctorCreditsRoute: typeof DoctorCreditsRoute
  DoctorHubRoute: typeof DoctorHubRouteWithChildren
  DoctorPlansRoute: typeof DoctorPlansRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorSessionsSessionIdRoute: typeof DoctorSessionsSessionIdRoute
  DoctorSessionsIndexRoute: typeof DoctorSessionsIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
  DoctorCreditsRoute: DoctorCreditsRoute,
  DoctorHubRoute: DoctorHubRouteWithChildren,
  DoctorPlansRoute: DoctorPlansRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorSessionsSessionIdRoute: DoctorSessionsSessionIdRoute,
  DoctorSessionsIndexRoute: DoctorSessionsIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface TenantRouteChildren {
  TenantCreateRoute: typeof TenantCreateRoute
  TenantIndexRoute: typeof TenantIndexRoute
  TenantTenantIdAttendanceRoute: typeof TenantTenantIdAttendanceRoute
  TenantTenantIdClinicsRoute: typeof TenantTenantIdClinicsRoute
  TenantTenantIdDoctorsRoute: typeof TenantTenantIdDoctorsRoute
  TenantTenantIdInviteRoute: typeof TenantTenantIdInviteRoute
  TenantTenantIdSettingsRoute: typeof TenantTenantIdSettingsRoute
  TenantTenantIdIndexRoute: typeof TenantTenantIdIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantCreateRoute: TenantCreateRoute,
  TenantIndexRoute: TenantIndexRoute,
  TenantTenantIdAttendanceRoute: TenantTenantIdAttendanceRoute,
  TenantTenantIdClinicsRoute: TenantTenantIdClinicsRoute,
  TenantTenantIdDoctorsRoute: TenantTenantIdDoctorsRoute,
  TenantTenantIdInviteRoute: TenantTenantIdInviteRoute,
  TenantTenantIdSettingsRoute: TenantTenantIdSettingsRoute,
  TenantTenantIdIndexRoute: TenantTenantIdIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TenantRoute: TenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
