/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DoctorSessionsRouteImport } from './routes/doctor/sessions'
import { Route as DoctorProfileRouteImport } from './routes/doctor/profile'
import { Route as DoctorPlansRouteImport } from './routes/doctor/plans'
import { Route as DoctorCreditsRouteImport } from './routes/doctor/credits'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor/availability'
import { Route as AdminSessionRouteImport } from './routes/admin/session'
import { Route as AdminDoctorsIndexRouteImport } from './routes/admin/doctors/index'
import { Route as AdminDocRequestsIndexRouteImport } from './routes/admin/doc-requests/index'
import { Route as DoctorSessionsSessionIdRouteImport } from './routes/doctor/sessions/$sessionId'
import { Route as AdminDoctorsDoctorIdRouteImport } from './routes/admin/doctors/$doctorId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DoctorSessionsRoute = DoctorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPlansRoute = DoctorPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorCreditsRoute = DoctorCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminSessionRoute = AdminSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsIndexRoute = AdminDoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocRequestsIndexRoute = AdminDocRequestsIndexRouteImport.update({
  id: '/doc-requests/',
  path: '/doc-requests/',
  getParentRoute: () => AdminRoute,
} as any)
const DoctorSessionsSessionIdRoute = DoctorSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => DoctorSessionsRoute,
} as any)
const AdminDoctorsDoctorIdRoute = AdminDoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/session': typeof AdminSessionRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/credits': typeof DoctorCreditsRoute
  '/doctor/plans': typeof DoctorPlansRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/sessions': typeof DoctorSessionsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/doctor/sessions/$sessionId': typeof DoctorSessionsSessionIdRoute
  '/admin/doc-requests/': typeof AdminDocRequestsIndexRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/session': typeof AdminSessionRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/credits': typeof DoctorCreditsRoute
  '/doctor/plans': typeof DoctorPlansRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/sessions': typeof DoctorSessionsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/doctor/sessions/$sessionId': typeof DoctorSessionsSessionIdRoute
  '/admin/doc-requests': typeof AdminDocRequestsIndexRoute
  '/admin/doctors': typeof AdminDoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/session': typeof AdminSessionRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/credits': typeof DoctorCreditsRoute
  '/doctor/plans': typeof DoctorPlansRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/sessions': typeof DoctorSessionsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/doctor/sessions/$sessionId': typeof DoctorSessionsSessionIdRoute
  '/admin/doc-requests/': typeof AdminDocRequestsIndexRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/sign-in'
    | '/sign-up'
    | '/admin/session'
    | '/doctor/availability'
    | '/doctor/credits'
    | '/doctor/plans'
    | '/doctor/profile'
    | '/doctor/sessions'
    | '/admin/'
    | '/doctor/'
    | '/admin/doctors/$doctorId'
    | '/doctor/sessions/$sessionId'
    | '/admin/doc-requests/'
    | '/admin/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin/session'
    | '/doctor/availability'
    | '/doctor/credits'
    | '/doctor/plans'
    | '/doctor/profile'
    | '/doctor/sessions'
    | '/admin'
    | '/doctor'
    | '/admin/doctors/$doctorId'
    | '/doctor/sessions/$sessionId'
    | '/admin/doc-requests'
    | '/admin/doctors'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/sign-in'
    | '/sign-up'
    | '/admin/session'
    | '/doctor/availability'
    | '/doctor/credits'
    | '/doctor/plans'
    | '/doctor/profile'
    | '/doctor/sessions'
    | '/admin/'
    | '/doctor/'
    | '/admin/doctors/$doctorId'
    | '/doctor/sessions/$sessionId'
    | '/admin/doc-requests/'
    | '/admin/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/doctor/sessions': {
      id: '/doctor/sessions'
      path: '/sessions'
      fullPath: '/doctor/sessions'
      preLoaderRoute: typeof DoctorSessionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/plans': {
      id: '/doctor/plans'
      path: '/plans'
      fullPath: '/doctor/plans'
      preLoaderRoute: typeof DoctorPlansRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/credits': {
      id: '/doctor/credits'
      path: '/credits'
      fullPath: '/doctor/credits'
      preLoaderRoute: typeof DoctorCreditsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/availability': {
      id: '/doctor/availability'
      path: '/availability'
      fullPath: '/doctor/availability'
      preLoaderRoute: typeof DoctorAvailabilityRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/session': {
      id: '/admin/session'
      path: '/session'
      fullPath: '/admin/session'
      preLoaderRoute: typeof AdminSessionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors/': {
      id: '/admin/doctors/'
      path: '/doctors'
      fullPath: '/admin/doctors/'
      preLoaderRoute: typeof AdminDoctorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doc-requests/': {
      id: '/admin/doc-requests/'
      path: '/doc-requests'
      fullPath: '/admin/doc-requests/'
      preLoaderRoute: typeof AdminDocRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/doctor/sessions/$sessionId': {
      id: '/doctor/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/doctor/sessions/$sessionId'
      preLoaderRoute: typeof DoctorSessionsSessionIdRouteImport
      parentRoute: typeof DoctorSessionsRoute
    }
    '/admin/doctors/$doctorId': {
      id: '/admin/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/admin/doctors/$doctorId'
      preLoaderRoute: typeof AdminDoctorsDoctorIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSessionRoute: typeof AdminSessionRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDoctorsDoctorIdRoute: typeof AdminDoctorsDoctorIdRoute
  AdminDocRequestsIndexRoute: typeof AdminDocRequestsIndexRoute
  AdminDoctorsIndexRoute: typeof AdminDoctorsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSessionRoute: AdminSessionRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDoctorsDoctorIdRoute: AdminDoctorsDoctorIdRoute,
  AdminDocRequestsIndexRoute: AdminDocRequestsIndexRoute,
  AdminDoctorsIndexRoute: AdminDoctorsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorSessionsRouteChildren {
  DoctorSessionsSessionIdRoute: typeof DoctorSessionsSessionIdRoute
}

const DoctorSessionsRouteChildren: DoctorSessionsRouteChildren = {
  DoctorSessionsSessionIdRoute: DoctorSessionsSessionIdRoute,
}

const DoctorSessionsRouteWithChildren = DoctorSessionsRoute._addFileChildren(
  DoctorSessionsRouteChildren,
)

interface DoctorRouteChildren {
  DoctorAvailabilityRoute: typeof DoctorAvailabilityRoute
  DoctorCreditsRoute: typeof DoctorCreditsRoute
  DoctorPlansRoute: typeof DoctorPlansRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorSessionsRoute: typeof DoctorSessionsRouteWithChildren
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
  DoctorCreditsRoute: DoctorCreditsRoute,
  DoctorPlansRoute: DoctorPlansRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorSessionsRoute: DoctorSessionsRouteWithChildren,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
